spring:
  datasource:
    url: jdbc:mysql://ikuns.live:3310/xxx?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root

  redis:
    host: ikuns.live
    database: 0
    port: 6379
    password: 32Qwer#1966@
    lettuce:
      pool:
        max-active: 8
        max-wait: 1000ms
        max-idle: 30
        min-idle: 10

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info

#minio 配置
minio:
  url: http://minioview.ikuns.live
  endpoint: http://ikuns.live:9090
  access-key: minious
  secret-key: qwe2580@
  bucketName: oj-b

# 代码沙箱配置
codesandbox:
  type: remote